### ISSUE TITLE
Polish readme files of all tools

### ISSUE THREAD

**Issue by SarahAlidoost** [RS-DAT/RS-DAT#7]
The readme of all repositories and RS-DAT repo should be polished. So, this can be done by submitting PRs to relevant repos.

**Comment by fnattino** [comment]
Also, we should think about including only absolute links, since they otherwise cannot be reached by the deployed documentation (e.g. a link `[user guide](./user_guide.md)` in the JupyterDaskOnSLURM/README.md would be broken in the overall RS-DAT docs..)
